### ISSUE TITLE
[1] Mundo de Jogo: Desenvolvimento do mapa da Praça Central

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#17]
Criar mapa detalhado para a área do jogo, considerando o design de níveis e a jogabilidade.
Criar sprites e assets pixelados para representar os elementos do mundo do jogo.
Implementar eventos e interações específicas para essa área.

**Comment by Yasmin-Camargo** [comment]
Implementado no commit c6efd9017eb9cd4cb3794a359e710f0ff291d254
