### ISSUE TITLE
[3] Mundo de Jogo: Implementar os pontos de colisão

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#19]
Implementar os pontos de colisão no código do jogo, garantindo que os personagens e objetos interajam corretamente com o ambiente dos dois mapas do jogo.

**Comment by Yasmin-Camargo** [comment]
Implementado no commit 159ef3a0224ea279c92f40a241fb58f78a5c05eb e f94bc07757759e283ddc8f7d200eb3d4ea3e3a4d
