### ISSUE TITLE
[1] Câmera: implementar a funcionalidade da câmera top-down no jogo

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#21]
Desenvolver algoritmos e scripts para permitir a visualização do campo de jogo em uma perspectiva Top-Down com rolagem.

**Comment by Yasmin-Camargo** [comment]
Desenvolvido no commit e6823ba7d2a72f9ba1a7f96ee7482c087aa6b3ab
