### ISSUE TITLE
[1] HUD: desenvolver habilidade e tempo de recarga

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#44]
Estilo Visual: Uma representação visual da habilidade atual e sua barra de recarga são exibidas de forma clara e destacada, com ícones que correspondem à natureza da habilidade. 

Funcionamento: A barra de recarga é atualizada conforme o jogador usa suas habilidades e é recalculada com base no tempo de recarga específico de cada habilidade.

**Comment by Yasmin-Camargo** [comment]
Implementado no commit ef90aac4130fce6e178a06ebcc96bd2ef6354bc1
