### ISSUE TITLE
[1] HUD: desenvolver mensagens do sistema

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#46]
Estilo Visual: As mensagens são exibidas abaixo da contagem regessiva e do nome da equipe, utilizando uma fonte legível e cores de destaque para garantir que sejam facilmente visíveis para os jogadores.

Funcionamento: As mensagens são exibidas de acordo com eventos específicos do jogo, como o congelamento e descogelamento de um jogador, garantindo que os jogadores sejam mantidos informados sobre os desenvolvimentos importantes durante a partida.

**Comment by Yasmin-Camargo** [comment]
resolvido no commit d2d46a7f00d03d5c5a583c36351815feb33eb2ef
