### ISSUE TITLE
[1] Personagens: desenvolvimento do personagem Bola de Pelos

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#49]
Habilidade: Esconderijo Felino
Descrição: pode se esconder em locais estratégicos, tornando-se temporariamente invisível para os Cachorros.
- O personagem do jogador se torna invisível para os Cachorros 
- A invisibilidade impede que os inimigos detectem ou ataquem o jogador enquanto a habilidade estiver ativa
- O indicador do personagem no minimapa é removido
- Enquanto estiver invisível, o jogador pode se movimentar furtivamente pelo ambiente
- Após o uso da habilidade, há um período de recarga durante o qual o jogador não pode ativá-la novamente

**Comment by Yasmin-Camargo** [comment]
Desenvolvido no commit 23e506c2d2c6f9f93f12d3663d58bc36a097dec3
