### ISSUE TITLE
[2] Personagens: desenvolvimento do personagem Sombra

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#50]
Habilidade: Ataque de Pelos
Descrição: Libera uma nuvem de pêlos fofos, obstruindo a visão dos Cachorros.
- A nuvem é representada visualmente por uma tela preta, obstruindo toda visão dos Cachorros incluindo mapa, adversários e amigos
- APENAS CACHORROS dentro da área afetada TEM A sua visibilidade prejudicada
- Após o uso da habilidade, há um período de recarga durante o qual o jogador não pode ativá-la novamente

**Comment by Yasmin-Camargo** [comment]
Desenvolvido no commit 23e506c2d2c6f9f93f12d3663d58bc36a097dec3
