### ISSUE TITLE
[3] Personagens: desenvolvimento do personagem Ronronante

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#51]
Habilidade: Ronronar calmante
Descrição: Emite um ronronar calmante que reduz temporariamente a velocidade dos Cachorros ao seu redor.

- Reduz Temporariamente EM 40% a velocidade dos Cachorros que estão dentro da área de efeito da habilidade.
- Proporciona ao jogador uma janela de oportunidade para escapar de situações perigosas 
- Após o uso da habilidade, há um período de recarga durante o qual o jogador não pode ativá-la novamente

**Comment by Yasmin-Camargo** [comment]
Desenvolvido no commit 23e506c2d2c6f9f93f12d3663d58bc36a097dec3
