### ISSUE TITLE
[4] Personagens: desenvolvimento do personagem Sargento Canis

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#52]
Habilidade: latido sônico
Descrição: Seu latido poderoso pode desorientar temporariamente os Gatinhos, TIRANDO A capacidade de usar habilidades.

- Remove temporariamente a capacidade dos Gatinhos de usar suas habilidades
- Imita as opções estratégicas dos Gatinhos durante o período em que estão afetados pelo latido sônico, tornando-os mais vulneráveis aos ataques do jogador

**Comment by Yasmin-Camargo** [comment]
Desenvolvido no commit c20fcbf99469d8cafef8bd7a1f02de2da9fbb874
