### ISSUE TITLE
[5] Personagens: desenvolvimento do personagem Estrela

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#60]
Habilidade: palmas saltitantes
Descrição: Pode correr em alta velocidade, encurtando a distância entre ela e os Gatinhos rapidamente.

- Permite que a personagem persiga os Gatinhos com MAIOR VELOCIDADE, reduzindo a chance de fuga.
- Encurta rapidamente a distância entre O PERSONAGEM e os Gatinhos
- Tempo limitado de uso ou uma quantidade limitada de cargas antes de exigir um período de recarga.

**Comment by Yasmin-Camargo** [comment]
Implementado no commit c6224b9452b007cfccc50edf988985b7a11da33a
