### ISSUE TITLE
[6] Personagens: desenvolvimento do personagem Brutus

### ISSUE THREAD

**Issue by Caroline-Camargo** [PixelCrafters-Team/PixelCrafters-Game#61]
Habilidade: Resistência Canina
Descrição: Resistente a distrações, sendo menos afetado pelas habilidades de distração dos Gatinhos.

- Enquanto a habilidade estiver ativa, os efeitos das habilidades de distração dos Gatinhos NÃO SURGEM EFEITO
- PermitE perseguir os Gatinhos alvo sem ser interrompida pelos efeitos das habilidades de distração.
- Tempo limitado de uso ou uma quantidade limitada de cargas antes de exigir um período de recarga.

**Comment by Yasmin-Camargo** [comment]
Implementado no commit c6224b9452b007cfccc50edf988985b7a11da33a
